#!/usr/bin/env python

import numpy as np

import rospy

from sensor_msgs.msg import LaserScan


def laserscan_handler(msg, transform):
    position = transform.dot(np.diag(list(msg.ranges)))
    print(' '.join(['{:.3f}'.format(x) for x in position[0, :]]))

if __name__ == '__main__':

    rospy.init_node('scan_test')

    beam_count = rospy.get_param('/leddar/beam_count')
    angle_min = rospy.get_param('/leddar/angle_min')
    angle_max = rospy.get_param('/leddar/angle_max')
    angle_inc = rospy.get_param('/leddar/angle_increment')

    transform = np.empty([3, 16])
    transform[0, :] = np.cos(np.linspace(angle_min, angle_max, beam_count))
    transform[1, :] = np.sin(np.linspace(angle_min, angle_max, beam_count))
    transform[2, :] = np.zeros(16)

    laserscan_sub = rospy.Subscriber('/leddar/scan', LaserScan, laserscan_handler, transform)
    rospy.spin()

